logging:
  level:
    root: info
    xyz.shoaky.sourcedownloader: debug

spring:
  config:
    import: ${SOURCE_DOWNLOADER_DATA_LOCATION:}config.yaml
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  datasource:
    username: sd
    password: sd
    url: jdbc:h2:file:${SOURCE_DOWNLOADER_DATA_LOCATION:./}source-downloader
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    open-in-view: false

  flyway:
    locations:
      - classpath:/db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  h2:
    console:
      enabled: true