components:
  downloader:
    - name: truenas
      type: qbittorrent
      props:
        url: http://truenas:10095
        username: admin
        password: adminadmin
  source:
    - name: mikan
      type: rss
      props:
        url: https://mikanani.me/RSS/Bangumi?bangumiId=2852&subgroupid=583
  source-content-creator:
    - name: mikan
      type: mikan
  file-mover:
    - name: truenas
      type: qbittorrent
  run-after-completion:
    - name: n8n-webhook-send-message
      type: script
      props:
        path: /app/data/script.sh
  trigger:
    - name: 20min
      type: fixed
      props:
        interval: PT20M
        on-start-run-tasks: false

processors:
  - name: mikan-bangumi
    trigger: fixed:20min
    source: rss:mikan
    creator: mikan
    downloader: qbittorrent:truenas
    mover: qbittorrent:truenas
    save-path: /mnt/bangumi
    options:
      #完成后运行
      run-after-completion:
        - script:n8n-webhook-send-message
      #可用变量具体看creator能提供什么
      file-save-path-pattern: "{originName}/Season {season}/"
      #可用变量具体看creator能提供什么
      filename-pattern: "S{season}E{episode} - {version}-{resolution}"
      #全局过滤非必填
      blacklist-regex:
        - 720P
        - 中文配音
      #重命名间隔时间,参考java.time.Duration的格式
      rename-task-interval: PT1M