name: Dev Docker Image
on:
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Manual trigger'
        required: false
#  push:
#    branches:
#      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '20'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew clean build -x test --no-daemon

      - name: Docker Metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: shoaky009/source-downloader
          tags: |
            type=raw,value=dev

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          builder: ${{ steps.buildx.output.name }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}