spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  datasource:
    username: sd
    password: sd
    url: jdbc:h2:file:${SOURCE_DOWNLOADER_DATA_LOCATION:./}source-downloader
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    open-in-view: false
  flyway:
    locations:
      - classpath:/db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

source-downloader:
  data-location: ${SOURCE_DOWNLOADER_DATA_LOCATION:./}

---
spring:
  config:
    activate:
      on-profile: debug
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    xyz.shoaky.sourcedownloader: debug
    org.hibernate.orm.jdbc.bind: trace

---
spring:
  config:
    activate:
      on-profile:
        - integration-test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE

source-downloader:
  data-location: src/test/resources