components:
  downloader:
    - name: qbittorrent
      type: qbittorrent
      props:
        url: http://truenas:20095
        username: shoaky
        password: 123456z
  source:
    - name: mikan
      type: rss
      props:
        url: https://mikanani.me/RSS/MyBangumi?token=L962oV%2bLsiabC6ZmTK4rOg%3d%3d
  file-mover:
    - name: qbittorrent
      type: qbittorrent
  run-after-completion:
    - name: n8n-webhook-send-message
      type: script
      props:
        path: /app/data/script.sh
  trigger:
    - name: dynamic
      type: dynamic
      props:
        bound-processors:
          - mikan-bangumi
#processors:
#  - name: mikan-bangumi
#    trigger: fixed:30min
#    source: rss:mikan
#    creator: mikan
#    downloader: mock
#    mover: general
#    save-path: /Users/shoaky/temp/save
#    options:
#      #完成后运行
#      run-after-completion:
#        - touchItemDirectory
##        - script:n8n-webhook-send-message
#      #可用变量具体看creator能提供什么
#      file-save-path-pattern: "{name}/Season {season}/"
#      #可用变量具体看creator能提供什么
#      filename-pattern: "{name-cn} - S{season}E{episode}"
#      #全局过滤非必填
#      blacklist-regex:
#        - '720(?i)P'
#        - '中文配音'
#      #重命名间隔时间,参考java.time.Duration的格式
#      rename-task-interval: PT1M