#放置常见没什么个性化配置的组件
file-mover:
  - name: general
    type: general
run-after-completion:
  - name: touch-item-directory
    type: touch-item-directory
  - name: clean-empty-directory
    type: clean-empty-directory
variable-provider:
  - name: metadata
    type: metadata
  - name: anitom
    type: anitom
  - name: season
    type: season
  - name: episode
    type: episode
trigger:
  - name: 30min
    type: fixed
    props:
      interval: PT30M
      on-start-run-tasks: true
  - name: 1hour
    type: fixed
    props:
      interval: PT1H
      on-start-run-tasks: true
  - name: 1day
    type: fixed
    props:
      interval: P1D
      on-start-run-tasks: true
  - name: webhook
    type: webhook
    props:
      path: default
file-tagger:
  - name: simple
    type: simple