#放置常见没什么个性化配置的组件
downloader:
  - name: url
    type: url
    props:
      download-path: ~/Downloads
  - name: mock
    type: mock
    props:
      download-path: ~/Downloads
file-mover:
  - name: general
    type: general
run-after-completion:
  - name: touchItemDirectory
    type: touchItemDirectory
variable-provider:
  - name: metadata
    type: metadata
  - name: anitom
    type: anitom
trigger:
  - name: 30min
    type: fixed
    props:
      interval: PT30M
      on-start-run-tasks: true
  - name: 1hour
    type: fixed
    props:
      interval: PT1H
      on-start-run-tasks: true
  - name: 1day
    type: fixed
    props:
      interval: P1D
      on-start-run-tasks: true
  - name: webhook
    type: webhook
    props:
      path: default